---
name: cmpsc-100-spring-2019-practical8
break: true
indent: 4
---
src/main:
    java:
        practicaleight/PasswordCheckerMain.java:
            --single 5 --language Java
            --multi 2 --language Java
            --fragment "new Date(" --count 1
            --fragment "println(" --count 5
            --fragment "new PasswordChecker(" --count 1
        practicaleight/PasswordChecker.java:
            --multi 4 --language Java
            --fragment "PASSWORD_MINIMUM_LENGTH" --count 1
            --fragment "println(" --count 0
            --fragment "if" --count 3
            --fragment "isValidLength" --count 2
            --fragment "isValidCapitalized" --count 2
            --fragment "isValidNumber" --count 2
--commits 3

--command "gradle -q --console plain run" --executes
